[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"
default-run = "aoc2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "*", features = ["full"] }
quote = "*"
proc-macro2 = "*"
