[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"
default-run = "aoc2023"

[lib]
proc-macro = true

[dependencies]
syn = { version = "*", features = ["full"] }
quote = "*"
proc-macro2 = "*"
regex = "1.10.2"
lazy_static = "1.4.0"
