[package]
name = "aoc{YEAR}"
version = "0.1.0"
edition = "2021"
default-run = "aoc{YEAR}"

[lib]
proc-macro = true

[dependencies]
syn = { version = "*", features = ["full"] }
quote = "*"
proc-macro2 = "*"
